baseurl: /project-2023-the-3-musketeers
url: https://com-480-data-visualization.github.io

title: How do you like your chocolate?
tagline: COM-480 Project
description: >- # this means to ignore newlines until "baseurl:"
  This website was created by Dana Kalaaji, Dong Chu, and Zhan Li. It is our submissiom for the COM-480 Data Visualization project.

  Chocolate Bar icon by Icons8.
cover: cover.jpg

categories_path: /categories/
tags_path: /tags/

remote_theme: vfvong/jekyll-theme-quartz
plugins:
  - jekyll-feed
  - jekyll-remote-theme